org: yomieth
app: web3
service: carato-api

frameworkVersion: "3"
useDotenv: true

custom:
  customDomain:
    domainName: carato-api.yomi.ninja
    basePath: ""
    stage: ${self:provider.stage}
    createRoute53Record: true

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: "20201221"
  stage: dev
  timeout: 90
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [caratoRequests, Arn]
        - Effect: Allow
          Action:
            - ssm:GetParametersByPath
            - ssm:GetParameter
            - ssm:GetParameters
          Resource: 
            - arn:aws:ssm:*:*:parameter/*
  environment:
    SECRET_PREFIX: "/carato-api"
    STAGE: ${sls:stage}

functions:
  api:
    handler: lambda.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

resources:
  Resources:
    caratoRequests:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: opId
            AttributeType: S
        KeySchema:
          - AttributeName: opId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${sls:stage}_caratoRequests

plugins:
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-plugin-typescript
  - serverless-domain-manager
